---
- hosts: localhost
  gather_facts: no
  tasks:
    - set_fact:
        images: ["{{ image }}"]
      when: image is string

    - include_tasks: tasks/build-image.yml
      with_items: "{{ images }}"
      loop_control:
        loop_var: image
