---
- hosts: localhost
  gather_facts: no
  vars:
    project: carafe
    registry: quay.io
  tasks:
    - set_fact:
        images: ["{{ image }}"]
      when: image is string

    - include_tasks: tasks/tag.yml
      with_items: "{{ images }}"
      loop_control:
        loop_var: image

    - include_tasks: tasks/push.yml
      with_items: "{{ images }}"
      loop_control:
        loop_var: image
